In [331]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor 
from sklearn.model_selection import train_test_split
import csv

In [332]:
def print_dir(obj):
    print((f"---| {obj.__class__} |---"))
    for i in dir(obj):
        if i.startswith("_"):
            continue
        print(i)

In [333]:
path = "D:\\projects\\Supervised-Learning-Experiments\\olympiads\\competition_samples\\raw\\romania-onia-examples\\Solutii\\Candidat_incepator"
train_df = pd.read_csv(f"{path}\\dataset_train.csv")
eval_df = pd.read_csv(f"{path}\\dataset_eval.csv")

In [334]:
train_df

,AppID,Name,Release date,Estimated owners,Price,Metacritic score,Recommendations,Positive,Negative,Publishers,Genres
0,350110,TransOcean 2: Rivals,"May 10, 2016",100000 - 200000,29.99,69,428,305,281,astragon Entertainment,"Simulation,Strategy"
1,312780,Way of the Samurai 4,"July 23, 2015",200000 - 500000,24.99,72,1475,1288,318,"Spike Chunsoft Co., Ltd.","Action,Adventure"
2,230150,Incredipede,"March 18, 2013",50000 - 100000,9.99,74,140,243,96,Northway Games,"Action,Adventure,Casual,Indie,Simulation"
3,1252300,RetroMania Wrestling,"February 25, 2021",0 - 20000,29.99,66,174,211,30,Retrosoft Studios,"Action,Sports"
4,760650,Hammerting,"November 16, 2021",100000 - 200000,9.99,64,1358,1328,705,Team17 Digital,"Adventure,Indie,RPG,Simulation,Strategy"
...,...,...,...,...,...,...,...,...,...,...,...
2995,266410,iRacing,"January 12, 2015",100000 - 200000,9.99,79,1281,2096,334,"iRacing.com Motorsport Simulations,iRacing","Massively Multiplayer,Racing,Simulation,Sports"
2996,939100,Darksburg,"September 23, 2020",100000 - 200000,14.99,61,1489,1511,750,Shiro Unlimited,"Action,Indie"
2997,1931770,Chants of Sennaar,"September 05, 2023",100000 - 200000,19.99,85,6125,6484,82,Focus Entertainment,"Adventure,Indie"
2998,41500,Torchlight,"October 27, 2009",1000000 - 2000000,14.99,83,4323,5424,495,Runic Games,RPG
2999,417290,Ghost of a Tale,"March 13, 2018",200000 - 500000,24.99,75,3268,3723,305,SeithCG,"Action,Adventure,Indie,RPG"

In [335]:
eval_df

,AppID,Name,Release date,Estimated owners,Metacritic score,Recommendations,Positive,Negative,Publishers,Genres
0,636230,Safe House,"May 22, 2018",0 - 20000,46,0,13,19,Labs Games,"Adventure,Indie,Strategy"
1,256460,Cosmic Star Heroine,"April 11, 2017",100000 - 200000,77,574,677,82,Zeboyd Games,"Indie,RPG"
2,327890,I Am Bread,"April 09, 2015",500000 - 1000000,60,4525,4359,1247,Bossa Studios,"Action,Adventure,Indie,Simulation"
3,287020,Harvester,"April 04, 2014",50000 - 100000,53,769,905,88,Nightdive Studios,Adventure
4,25980,Majesty 2,"September 17, 2009",200000 - 500000,72,783,611,270,Paradox Interactive,"Simulation,Strategy"
...,...,...,...,...,...,...,...,...,...,...
595,269650,Dex,"May 07, 2015",200000 - 500000,62,2469,2655,389,"Dreadlocks Ltd.,Techland,WhisperGames","Action,Adventure,Indie,RPG"
596,261900,The Real Texas,"July 12, 2016",0 - 20000,74,0,28,2,Kitty Lambda Games Inc.,"Action,Adventure,Indie,RPG"
597,209630,Magrunner: Dark Pulse,"June 20, 2013",200000 - 500000,70,314,702,254,Frogwares,"Action,Adventure,Indie"
598,578650,The Outer Worlds,"October 23, 2020",500000 - 1000000,82,17319,16925,2891,Private Division,RPG
599,1122120,STATIONflow,"April 15, 2020",50000 - 100000,74,396,366,53,DMM GAMES,"Simulation,Strategy"

In [336]:
# print_dir(np.ndarray)

In [337]:
train_df_numpy = train_df.to_numpy()
samples = len(train_df)
print(samples)
average_price = int(train_df["Price"].mean())
print(average_price)
owners = np.array([(int(j[1]) + int(j[0]))//2 for j in [i.split("-") for i in train_df["Estimated owners"]]])
eval_owners = np.array([(int(j[1]) + int(j[0]))//2 for j in [i.split("-") for i in eval_df["Estimated owners"]]])
average_owners = sum(owners)//len(train_df)
print(average_owners)

unique_gernes = []
for gernes in train_df["Genres"]:
    for gerne in gernes.split(","):
        unique_gernes.append(gerne)
unique_gernes_count = len(np.unique(np.array(unique_gernes)))
print(unique_gernes_count)

3000
16
628183
16

In [338]:
X_eval = np.concatenate((
    eval_owners.reshape(-1, 1), 
    eval_df["Metacritic score"].to_numpy().reshape(-1,1),
    eval_df["Recommendations"].to_numpy().reshape(-1,1),
    eval_df["Positive"].to_numpy().reshape(-1,1),
    eval_df["Negative"].to_numpy().reshape(-1,1),
    ), axis=1)
X = np.concatenate((
    owners.reshape(-1, 1), 
    train_df["Metacritic score"].to_numpy().reshape(-1,1),
    train_df["Recommendations"].to_numpy().reshape(-1,1),
    train_df["Positive"].to_numpy().reshape(-1,1),
    train_df["Negative"].to_numpy().reshape(-1,1),
    ), axis=1)
y = train_df["Price"].to_numpy()
print(X)
print(y.dtype)

[[ 150000      69     428     305     281]
 [ 350000      72    1475    1288     318]
 [  75000      74     140     243      96]
 ...
 [ 150000      85    6125    6484      82]
 [1500000      83    4323    5424     495]
 [ 350000      75    3268    3723     305]]
float64

In [339]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=.2)

In [340]:
model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train);
y_pred_test = model.predict(X_test)
loss = np.abs(y_test-y_pred_test).mean()
print(loss)

7.598781166666664

In [341]:
model.fit(X, y);
y_eval = model.predict(X_eval).tolist()
print(y_eval)

[9.110000000000007, 9.333600000000006, 13.998000000000006, 11.734600000000007, 11.018500000000008, 10.955000000000007, 13.540000000000006, 13.680000000000007, 14.290100000000006, 10.290000000000006, 20.10000000000001, 16.580000000000005, 9.702000000000007, 18.577500000000008, 18.960000000000008, 14.571000000000009, 7.605, 14.060000000000008, 12.284500000000007, 13.785000000000007, 20.470000000000006, 17.577500000000008, 14.470000000000006, 15.820000000000007, 15.921000000000008, 17.905500000000007, 12.610000000000007, 18.880000000000006, 14.087500000000007, 11.197000000000008, 18.868100000000005, 12.071000000000005, 15.420000000000007, 13.372000000000007, 9.945000000000007, 20.862500000000004, 19.795000000000005, 9.800000000000006, 11.671400000000006, 8.998600000000005, 23.079999999999988, 24.309999999999974, 20.595500000000005, 8.640000000000008, 18.91380000000001, 13.910000000000007, 12.900000000000007, 7.870000000000005, 9.478100000000007, 41.82499999999989, 33.47999999999992, 20.145000000000007, 28.88999999999994, 7.252500000000005, 18.0115, 22.852499999999992, 10.711000000000007, 8.805000000000007, 12.217500000000006, 19.468000000000007, 23.78499999999997, 16.570500000000006, 21.653999999999993, 8.455000000000007, 19.180000000000007, 20.260000000000005, 11.173500000000008, 19.255100000000006, 11.562000000000006, 20.555000000000003, 15.652500000000007, 16.31940000000001, 23.27499999999998, 13.959600000000007, 38.189999999999905, 15.970000000000006, 18.066600000000008, 9.445900000000007, 21.789999999999992, 18.625000000000007, 19.93340000000001, 14.810000000000008, 33.92499999999991, 9.900000000000007, 17.637000000000004, 15.513000000000007, 26.149999999999956, 13.399000000000008, 27.638499999999954, 11.737100000000007, 18.595000000000006, 13.750000000000007, 11.123100000000006, 10.985000000000007, 11.559000000000008, 23.317499999999974, 13.422500000000007, 12.608000000000011, 11.025000000000007, 21.56999999999999, 10.410000000000007, 10.585000000000006, 25.87999999999996, 14.780000000000006, 24.98799999999997, 13.415000000000006, 10.232000000000006, 19.282000000000007, 15.730000000000008, 13.105200000000004, 8.428200000000007, 21.46799999999999, 31.196499999999936, 23.756899999999973, 13.580000000000007, 12.408600000000009, 9.832500000000008, 25.039999999999967, 8.321500000000007, 46.10249999999989, 15.292500000000008, 17.545000000000005, 9.925500000000007, 10.232900000000008, 11.105800000000006, 18.037800000000008, 14.310000000000008, 24.261999999999972, 17.841400000000007, 14.600000000000007, 17.987500000000008, 11.340000000000007, 22.702499999999986, 11.753500000000006, 29.794999999999938, 12.020000000000007, 27.297699999999946, 13.169500000000006, 20.113800000000012, 15.395000000000007, 11.267500000000007, 16.117000000000008, 18.206300000000006, 19.903900000000007, 17.975400000000008, 12.321500000000007, 16.320000000000007, 11.016900000000005, 16.325000000000006, 15.21280000000001, 15.662500000000007, 19.51250000000001, 17.570200000000007, 23.765999999999977, 18.160000000000007, 9.749700000000006, 15.006700000000007, 24.004999999999974, 9.845000000000006, 11.910000000000007, 28.02999999999995, 13.700500000000009, 13.074000000000007, 5.037500000000006, 17.810000000000006, 9.724500000000006, 11.036000000000007, 21.4653, 12.470000000000006, 10.43030000000001, 17.520000000000007, 17.955000000000005, 11.635000000000007, 18.880000000000006, 12.338200000000006, 13.150000000000007, 17.105000000000008, 23.15679999999998, 6.336000000000006, 9.810500000000008, 19.579600000000006, 16.86380000000001, 12.222000000000007, 17.284600000000008, 16.78000000000001, 16.875000000000007, 21.615999999999996, 25.04999999999997, 29.209999999999937, 12.225000000000007, 17.066700000000008, 14.752000000000002, 20.707700000000003, 11.070000000000007, 18.320000000000007, 8.361200000000007, 14.555500000000006, 10.070000000000007, 21.652599999999993, 18.210000000000008, 13.597000000000007, 7.850000000000006, 13.132500000000007, 27.516999999999953, 20.22500000000001, 12.730000000000008, 6.896000000000007, 21.852999999999998, 10.476400000000005, 14.966000000000006, 8.794000000000006, 12.495500000000007, 16.867500000000007, 19.60600000000001, 12.831000000000007, 16.297000000000008, 23.178999999999977, 18.607500000000005, 10.820000000000007, 6.473600000000007, 12.362500000000006, 9.305000000000007, 28.141999999999943, 14.427500000000007, 22.399999999999988, 10.050000000000006, 17.029400000000006, 13.600200000000006, 42.569399999999895, 19.000000000000007, 10.895000000000007, 33.90399999999993, 14.467500000000006, 6.580000000000007, 10.626500000000007, 10.862000000000005, 12.611900000000007, 17.743800000000007, 30.542499999999936, 13.625800000000005, 12.700000000000006, 16.140000000000008, 17.017000000000007, 19.450000000000006, 20.41250000000001, 24.67499999999997, 12.304000000000007, 13.130000000000006, 20.970499999999998, 28.539499999999947, 15.635000000000007, 7.6165000000000065, 10.552900000000006, 10.523000000000009, 19.830000000000005, 17.881000000000007, 15.865000000000007, 9.66500000000001, 18.232500000000005, 13.412000000000008, 20.340000000000007, 18.555000000000007, 10.197400000000009, 14.67270000000001, 11.477500000000006, 22.950299999999984, 14.466400000000005, 11.734000000000007, 9.462500000000007, 8.330000000000005, 9.640000000000008, 18.490000000000006, 14.320000000000007, 25.95499999999996, 14.372500000000008, 25.50999999999996, 13.777000000000008, 16.57, 18.052500000000006, 17.495000000000008, 18.058000000000007, 7.832000000000006, 9.305400000000006, 16.671000000000006, 12.691000000000006, 35.549999999999905, 14.064000000000007, 11.125000000000007, 13.600000000000007, 13.088000000000006, 19.28000000000001, 10.408500000000009, 25.840499999999956, 9.532500000000006, 20.575000000000003, 17.795500000000008, 8.519400000000008, 20.330000000000005, 17.605000000000008, 23.79379999999998, 17.360000000000007, 12.760000000000007, 20.453900000000008, 13.347500000000007, 15.481800000000005, 17.692500000000006, 14.355000000000008, 18.940600000000007, 20.8, 12.695000000000007, 18.86080000000001, 16.143200000000007, 9.360000000000007, 11.690000000000007, 13.511200000000006, 17.078500000000005, 9.858100000000006, 13.090000000000007, 14.020000000000007, 27.509999999999945, 17.052400000000006, 16.680000000000007, 38.0699999999999, 9.714000000000006, 21.4642, 15.112500000000006, 18.735000000000007, 24.390999999999973, 14.645000000000007, 17.610000000000007, 19.247500000000006, 11.351500000000009, 18.46750000000001, 17.505000000000006, 15.600000000000007, 23.769999999999982, 20.640100000000007, 11.243500000000006, 10.683000000000007, 19.494000000000007, 25.91749999999997, 8.820000000000007, 12.374000000000008, 22.544999999999987, 22.404999999999994, 11.031600000000005, 10.680000000000007, 21.362799999999996, 8.605000000000008, 24.904999999999962, 12.820000000000007, 19.139000000000006, 26.317999999999962, 15.542500000000008, 10.030000000000006, 10.285000000000007, 33.083499999999916, 9.890000000000008, 14.260000000000007, 17.060000000000006, 20.529000000000007, 26.063099999999952, 10.228500000000007, 18.322500000000005, 14.215000000000007, 17.19000000000001, 21.1371, 24.893399999999975, 14.292500000000008, 21.99699999999999, 25.481399999999958, 14.105000000000004, 18.196700000000007, 21.08, 20.310000000000006, 22.965099999999985, 11.442000000000007, 12.969500000000007, 14.957500000000007, 17.429000000000006, 27.113299999999953, 14.882400000000004, 31.16779999999993, 15.568000000000007, 21.669999999999995, 17.620000000000008, 20.372500000000006, 8.110000000000007, 31.119999999999933, 23.654999999999976, 8.740000000000007, 15.870000000000006, 11.534700000000008, 8.466500000000007, 10.126000000000007, 17.839700000000008, 10.930000000000007, 11.188300000000005, 19.06500000000001, 19.12750000000001, 21.074699999999996, 19.613000000000007, 19.360000000000007, 20.809500000000007, 25.21629999999997, 10.422400000000005, 20.730100000000004, 14.795000000000007, 15.010000000000007, 18.89480000000001, 16.417500000000008, 13.900000000000007, 28.46499999999994, 17.075000000000006, 14.620000000000006, 7.592100000000006, 10.721000000000005, 26.234999999999953, 43.014999999999894, 16.99900000000001, 13.427000000000007, 24.019999999999968, 16.482300000000006, 11.382600000000007, 12.875000000000007, 30.29709999999993, 13.840000000000007, 37.4849999999999, 15.800000000000006, 8.658100000000008, 18.200000000000006, 23.989999999999977, 13.180000000000007, 7.998000000000006, 10.395000000000007, 16.01440000000001, 10.556300000000007, 12.701500000000008, 10.370000000000006, 8.536000000000007, 13.070000000000007, 22.82999999999998, 25.559999999999967, 9.450000000000008, 8.781000000000008, 25.34799999999996, 12.400000000000007, 14.925000000000006, 10.410000000000007, 12.174500000000007, 16.475400000000004, 26.580499999999965, 12.570000000000007, 13.212000000000007, 18.922000000000008, 11.380000000000006, 6.4054000000000055, 17.248800000000006, 23.074999999999985, 15.600000000000007, 10.561000000000009, 11.700000000000006, 27.479999999999954, 12.239600000000006, 12.660700000000006, 13.177500000000007, 17.215000000000007, 23.010199999999983, 11.380200000000007, 10.565000000000007, 11.330000000000007, 41.7074999999999, 16.915000000000006, 20.925800000000002, 16.930000000000007, 21.54999999999999, 23.626899999999978, 38.4524999999999, 18.135000000000005, 16.813000000000002, 20.9888, 23.607499999999977, 29.622499999999942, 12.430000000000007, 9.970000000000006, 38.21979999999991, 15.471000000000009, 11.460000000000006, 12.950100000000006, 25.06499999999996, 18.28140000000001, 19.110000000000007, 22.62359999999999, 21.670999999999996, 10.531600000000005, 10.848000000000006, 11.086700000000008, 9.352000000000007, 13.230000000000008, 12.580000000000007, 17.410000000000007, 13.190000000000007, 19.107500000000005, 13.980000000000008, 9.880000000000008, 13.467700000000006, 23.03749999999998, 28.68749999999994, 16.515000000000008, 15.316000000000006, 12.480000000000008, 28.01999999999995, 10.762300000000009, 19.617500000000007, 53.967499999999866, 15.022000000000007, 20.263000000000005, 14.155100000000006, 12.144100000000007, 23.36049999999997, 12.997000000000007, 24.149999999999974, 15.974400000000008, 15.246000000000008, 9.347800000000007, 25.10499999999997, 16.555000000000007, 20.965000000000003, 20.25700000000001, 11.562500000000007, 13.740000000000007, 19.15500000000001, 17.367500000000007, 15.440000000000007, 27.15999999999995, 13.465000000000007, 11.971300000000006, 12.854000000000008, 23.45099999999998, 11.835000000000006, 9.425000000000006, 9.399500000000005, 10.964500000000008, 11.150100000000007, 15.857100000000008, 9.926000000000007, 25.624999999999964, 14.500000000000007, 13.645000000000007, 12.311000000000005, 14.070000000000007, 9.614000000000006, 19.930000000000007, 38.56249999999991, 15.086000000000006, 33.97999999999991, 17.735000000000007, 10.304000000000007, 10.097500000000005, 25.128499999999963, 27.26479999999996, 10.596000000000005, 14.023000000000007, 10.820000000000007, 11.710000000000006, 16.560000000000006, 23.739999999999977, 17.034000000000006, 28.239999999999945, 18.495000000000008, 26.542499999999958, 7.370000000000005, 12.230900000000009, 14.090000000000007, 11.988000000000007, 14.983500000000008, 8.590000000000009, 16.099500000000006, 12.951600000000006, 19.165000000000006, 14.642200000000008, 18.200000000000006, 10.206600000000007, 18.845000000000006, 13.074000000000007, 11.206700000000007, 9.878500000000008, 8.189300000000008, 19.542500000000008, 24.506699999999974, 15.145500000000006, 14.793200000000008, 14.415400000000007, 25.109999999999964, 16.750000000000007, 11.888900000000005, 13.070000000000007, 10.047500000000007, 29.66249999999994, 11.610000000000007]

In [342]:
with open("output_1.csv", "w", newline="") as csvfile:
    fieldnames = "Samples","Average Price","Average Owners","Unique Genres"
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows([{"Samples":samples, "Average Price":average_price, "Average Owners":average_owners, "Unique Genres":unique_gernes_count}])

In [343]:
with open("output_2.csv", "w", newline="") as csvfile:
    fieldnames = ["Price"]
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    for i in y_eval:
        writer.writerows([{"Price":i}])